vich_uploader:
    db_driver: orm

    mappings:
        carousels:
            uri_prefix: /images/carousels
            upload_destination: "%kernel.project_dir%/public/images/carousels"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        auteurices:
            uri_prefix: /images/auteurices
            upload_destination: "%kernel.project_dir%/public/images/auteurices"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true